<!-- Js Plugins -->
<script src="{{ asset('public/assets/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('public/assets/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery.nice-select.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('public/assets/js/jquery.slicknav.js') }}"></script>
<script src="{{ asset('public/assets/js/mixitup.min.js') }}"></script>
<script src="{{ asset('public/assets/js/owl.carousel.min.js') }}"></script>
<script src="{{ asset('public/assets/js/main.js') }}"></script>